### ISSUE TITLE
Bazelisk could not create directory /home/ubuntu/.cache/bazelisk: mkdir /home/ubuntu/.cache: file exists

### ISSUE THREAD

**Issue by Zemnmez** [containerbase/base#3590]
It seems like since https://github.com/containerbase/base/releases/tag/12.0.0 bazelisk is broken because `/home/ubuntu/.cache` is a symlink, resulting in some strange behaviour:

```
cat: /home/ubuntu/.cache: No such file or directory
cat: /home/ubuntu/.cache/bazelisk: No such file or directory
2024/11/11 06:50:53 could not create directory /home/ubuntu/.cache/bazelisk: mkdir /home/ubuntu/.cache: file exists
cat: /home/ubuntu/.cache: No such file or directory
cat: /home/ubuntu/.cache/bazelisk: No such file or directory
```

It looks like it was caused by https://github.com/containerbase/base/issues/2988 -- it looks like the cache coercion patch hasn't applied to bazelisk:

https://github.com/containerbase/base/tree/0a35a788ef2b3577670878b193278f7cd53dbd53/src/usr/local/containerbase/tools/v2

I'm going to try pinning to an earlier version of `base`.

**Comment by rarkins** [comment]
Are you sure it's not because of permissions?

**Comment by Zemnmez** [comment]
It could be. I don't know how I would find that out. Happy to take advice.

**Comment by rarkins** [comment]
Are you caching any data between runs?

**Comment by Zemnmez** [comment]
This is my [config](https://github.com/zemn-me/monorepo/blob/dc9c84ca44223218302a342ec5283de97c6fb4ab/.github/workflows/renovate.yml):

```yaml
---


name: Renovate
concurrency:
  # if another instance of renovate is running,
  # do not attempt to run overlapping instances.
  group: renovate
on: # yamllint disable-line rule:truthy
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@67a664fc9b4481b33a3eff6ee9edfb7a7b9dfa1e # v41.0.2
        with:
          configurationFile: renovate.json
          renovate-version: full
          token: ${{ secrets.GH_PAT }}
    env:
      LOG_LEVEL: 'debug'
```
